title: "The Video Game Metadata Project"
description: "A user maintained bridge database connecting various video game databases such as Redump and MobyGames."
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one